void GenerateRandomData(int a[], int n);
void GenerateSortedData(int a[], int n);
void GenerateReverseData(int a[], int n);
void GenerateNearlySortedData(int a[], int n);
void GenerateData(int a[], int n, int dataType);
double MergeSort_Timing(int a[], int n);
void MergeSort_Compare(int theArray[], int n, int first, int last, int &compare);
double QuickSort_Timing(int a[], int n);
void QuickSort_Compare(int a[], int first, int last, int &compare);
double CountingSort_Timing(int arr[], int n);
double FlashSort_Timing(int arr[], int n);